apiVersion: v1
kind: ConfigMap
metadata:
  name: "config-tomom"
  namespace: "agents-dev"
data:
  AGENT_ID: "tomom"
  TEAM_NAME: "dev"
  PLATFORM_REGISTRY_URL: "https://apim-shop-poc.azure-api.net"
  KEYVAULT_URL: "https://kv-shop-poc.vault.azure.net/"
  AZURE_OPENAI_ENDPOINT: "https://oai-shop-poc.openai.azure.com/"
  AZURE_OPENAI_DEPLOYMENT: "gpt-4o"
  OTEL_SERVICE_NAME: "tomom"
